# Generated by Django 2.1.2 on 2018-10-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_meetup_id', models.CharField(default='', max_length=32)),
                ('reservation_limit', models.IntegerField(default=100)),
                ('headcount', models.IntegerField(default=0)),
                ('visibility', models.CharField(max_length=10)),
                ('waitlistcount', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('event_url', models.CharField(max_length=250)),
                ('yes_reservation_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('photo', models.ImageField(default='event_pics/default.png', upload_to='event_pics')),
                ('time', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('status', models.CharField(default='upcoming', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(default='EU', max_length=10)),
                ('label', models.CharField(default='price', max_length=30)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_meetup_id', models.CharField(default='', max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('repinned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventFee'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventVenue'),
        ),
    ]
