# Generated by Django 2.1.2 on 2019-02-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_meetup_id', models.CharField(default='', max_length=32)),
                ('reservation_limit', models.IntegerField(default=100)),
                ('headcount', models.IntegerField(default=0)),
                ('visibility', models.CharField(max_length=10)),
                ('waitlist_count', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('event_url', models.CharField(max_length=250)),
                ('yes_reservation_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('time', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('status', models.CharField(default='upcoming', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=events.models.get_current_datetime)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDrawParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=events.models.get_current_datetime)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventCheckIn')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventDraw')),
            ],
        ),
        migrations.CreateModel(
            name='EventFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(default='EU', max_length=10)),
                ('label', models.CharField(default='price', max_length=30)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_meetup_id', models.CharField(default='', max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('repinned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventFee'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventVenue'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdrawparticipation',
            unique_together={('checkin', 'draw')},
        ),
        migrations.AlterUniqueTogether(
            name='eventcheckin',
            unique_together={('account', 'event')},
        ),
    ]
