# Generated by Django 2.1.2 on 2018-10-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='event_meetup_id',
            field=models.IntegerField(default=0),
        ),
    ]
