# Generated by Django 2.1.2 on 2018-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181027_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
