# Generated by Django 2.1.2 on 2018-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181027_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='event_pics/default.png', upload_to='event_pics'),
        ),
    ]
