# Generated by Django 2.1.2 on 2018-11-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='checked_in',
        ),
    ]
